"use strict";

// Focused App Shell / Pages regressions. Run with `npm test` on Node 22.
// Uses only Node built-ins: no external requests, credentials, or test dependencies.
const assert = require("node:assert/strict");
const crypto = require("node:crypto");
const fs = require("node:fs");
const os = require("node:os");
const path = require("node:path");
const { test } = require("node:test");

const ROOT = path.resolve(__dirname, "..");
const SHELL = path.join(ROOT, "vendor", "marinos");
const manifest = JSON.parse(fs.readFileSync(path.join(SHELL, "manifest.json"), "utf8"));
const appManifest = fs.readFileSync(path.join(ROOT, "marin.yml"), "utf8");
const workflow = fs.readFileSync(path.join(ROOT, ".github/workflows/build-and-deploy.yml"), "utf8").replace(/\r\n?/g, "\n");
const html = fs.readFileSync(path.join(ROOT, "index.html"), "utf8");

function containedPath(base, relative) {
  const resolved = path.resolve(base, relative);
  const remainder = path.relative(base, resolved);
  assert.ok(remainder && remainder !== ".." && !remainder.startsWith(`..${path.sep}`) && !path.isAbsolute(remainder),
    `Path must remain inside ${base}: ${relative}`);
  return resolved;
}

function checkManagedFiles(base, entries) {
  assert.ok(entries && Object.keys(entries).length, "Managed-file inventory must not be empty");
  for (const [relative, expected] of Object.entries(entries)) {
    const file = containedPath(base, relative);
    assert.ok(fs.existsSync(file), `Missing managed asset: ${relative}. Reinstall the complete App Shell runtime.`);
    const bytes = fs.readFileSync(file);
    assert.equal(bytes.length, expected.bytes, `Managed-file size differs: ${relative}`);
    assert.equal(crypto.createHash("sha256").update(bytes).digest("hex"), expected.sha256,
      `Managed-file hash differs: ${relative}. Do not edit generated files or their recorded hashes.`);
  }
}

function attribute(tag, name) {
  return tag.match(new RegExp(`\\b${name}\\s*=\\s*(["'])(.*?)\\1`, "i"))?.[2];
}

// Inspect only the simple direct scalars used by this app's manifest.
// This is intentionally not a general YAML parser. The shell itself also
// reads project.status as a direct, two-space-indented scalar.
function manifestScalar(section, key) {
  const lines = appManifest.split(/\r?\n/);
  let active = false;
  for (const line of lines) {
    if (!line.trim() || line.trimStart().startsWith("#")) continue;
    if (!active) {
      active = new RegExp(`^${section}\\s*:\\s*(?:#.*)?$`).test(line);
      continue;
    }
    if (!/^\s/.test(line)) break;
    const match = line.match(new RegExp(`^ {2}${key}\\s*:\\s*(?:"([^"]*)"|'([^']*)'|([^#]*?))\\s*(?:#.*)?$`));
    if (match) return (match[1] ?? match[2] ?? match[3]).trim();
  }
  assert.fail(`Missing or unsupported ${section}.${key} in marin.yml`);
}

function stagingInputs() {
  const stage = workflow.match(/^      - name: Stage static site\r?\n        run: \|\r?\n((?: {10}[^\n]*\n?)+)/m);
  assert.ok(stage, "Workflow must have an explicit Stage static site run block");
  const copy = stage[1].match(/^\s*cp -r ([\w./ -]+?) dist\/\s*$/m);
  assert.ok(copy, "Review this test when changing the workflow's explicit static copy command");
  return copy[1].trim().split(/\s+/);
}

function assertLocalReferences(stagedRoot) {
  for (const [tag] of html.matchAll(/<(?:script|link)\b[^>]*>/gi)) {
    const reference = attribute(tag, "src") || attribute(tag, "href");
    if (!reference || /^(?:[a-z][a-z\d+.-]*:|\/\/|#)/i.test(reference)) continue;
    // This link is generated by the separate ingestion step, not copied.
    if (reference === "feeds/all.xml") continue;
    const localPath = decodeURIComponent(reference.split(/[?#]/)[0]);
    assert.ok(fs.existsSync(containedPath(stagedRoot, localPath)), `Unpublished HTML asset: ${reference}`);
  }
  const cssPath = path.join(stagedRoot, "vendor/marinos/marinos.css");
  const css = fs.readFileSync(cssPath, "utf8");
  for (const [, raw] of css.matchAll(/url\(\s*([^)]+?)\s*\)/g)) {
    const reference = raw.replace(/^["']|["']$/g, "");
    if (/^(?:[a-z][a-z\d+.-]*:|\/\/|#)/i.test(reference)) continue;
    const file = path.resolve(path.dirname(cssPath), decodeURIComponent(reference.split(/[?#]/)[0]));
    assert.ok(fs.existsSync(file), `Unpublished CSS asset: ${reference}`);
  }
}

test("marin.yml agrees with the installed shell and declares a supported release status", () => {
  assert.equal(manifestScalar("platform", "shell"), manifest.shellVersion);
  assert.equal(manifest.installPath, "vendor/marinos");
  assert.ok(["alpha", "beta", "live"].includes(manifestScalar("project", "status").toLowerCase()));
});

test("generated App Shell files match their release hashes", () => {
  checkManagedFiles(SHELL, manifest.files);
});

test("managed font and icon companions match the complete runtime manifest", () => {
  checkManagedFiles(ROOT, manifest.fontAssets);
  checkManagedFiles(ROOT, manifest.companionIcons);
});

test("the entry point loads one bundled shell in the correct order", () => {
  const stylesheets = Array.from(html.matchAll(/<link\b[^>]*>/gi), ([tag]) => tag)
    .filter((tag) => attribute(tag, "rel") === "stylesheet")
    .map((tag) => attribute(tag, "href"));
  assert.deepEqual(stylesheets, ["vendor/marinos/marinos.css", "assets/app.css"]);

  const scripts = Array.from(html.matchAll(/<script\b[^>]*>/gi), ([tag]) => ({ tag, src: attribute(tag, "src") }));
  const shellScripts = scripts.filter((script) => script.src === "vendor/marinos/marinos.js");
  const appScripts = scripts.filter((script) => script.src === "assets/app.js");
  assert.equal(shellScripts.length, 1);
  assert.equal(appScripts.length, 1);
  for (const script of [...shellScripts, ...appScripts]) {
    assert.match(script.tag, /\bdefer\b/, `${script.src} must be deferred`);
    assert.doesNotMatch(script.tag, /\basync\b/, `${script.src} must retain ordered execution`);
  }
  assert.ok(scripts.indexOf(shellScripts[0]) < scripts.indexOf(appScripts[0]));
  assert.ok(scripts.some((script) => script.src === "vendor/chart.min.js"), "Keep the app's local Chart.js dependency");
  assert.doesNotMatch(html, /(?:src|href)\s*=\s*["'](?:\.\/)?(?:shared\/|vendor\/pico)/i);
  assert.match(html, /<marin-app-header\b/);
});

test("app CSS does not duplicate or override standard release-status badge styles", () => {
  const css = fs.readFileSync(path.join(ROOT, "assets/app.css"), "utf8").replace(/\/\*[\s\S]*?\*\//g, "");
  assert.doesNotMatch(css, /\.app-status\b|\.app-title__status\b|\[data-(?:marinos-)?status\b/);
  assert.match(css, /\.mm-card__meta\s+\.app-badge\s*\{\s*font-weight:\s*400\s*;\s*\}/,
    "Preserve the existing app-scoped metadata badge styling");
});

test("Pages stages required runtime files, validates first, and retains the live snapshot merge", () => {
  const inputs = stagingInputs();
  for (const expected of ["index.html", "assets", "vendor", "security.json", "marin.yml", ".well-known"]) {
    assert.ok(inputs.includes(expected), `Workflow must stage ${expected}`);
  }
  for (const input of inputs) assert.ok(fs.existsSync(containedPath(ROOT, input)), `Missing static copy input: ${input}`);
  assert.ok(!inputs.includes("shared"), "Do not restore the retired application-level directory");

  const validation = workflow.indexOf("run: npm test");
  const staging = workflow.indexOf("- name: Stage static site");
  const ingestion = workflow.indexOf("node build/index.js");
  assert.ok(validation >= 0 && validation < staging && staging < ingestion);
  assert.match(workflow, /--out=dist\/data\.json/);
  assert.ok(workflow.includes(
    '--previous="https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/data.json"'
  ), "Keep the existing production previous-snapshot URL");
  assert.match(workflow, /uses: actions\/upload-pages-artifact@[^\n]+\n\s+with:\n\s+path: dist\s*(?:\n|$)/);

});

test("staging includes the complete local runtime and excludes build-only files", (t) => {
  const tmp = fs.mkdtempSync(path.join(os.tmpdir(), "marin-mentions-shell-"));
  t.after(() => fs.rmSync(tmp, { recursive: true, force: true }));
  const dist = path.join(tmp, "dist");
  fs.mkdirSync(dist);
  // Mirror the exact workflow inputs using cross-platform Node copies.
  // Ingestion and external connectors are intentionally outside this suite.
  for (const input of stagingInputs()) {
    fs.cpSync(containedPath(ROOT, input), containedPath(dist, input), { recursive: true });
  }
  assertLocalReferences(dist);
  checkManagedFiles(path.join(dist, "vendor/marinos"), manifest.files);
  checkManagedFiles(dist, manifest.fontAssets);
  checkManagedFiles(dist, manifest.companionIcons);
  assert.equal(fs.readFileSync(path.join(dist, "marin.yml"), "utf8"), appManifest);
  assert.ok(fs.existsSync(path.join(dist, "security.json")));
  assert.ok(fs.existsSync(path.join(dist, ".well-known/security.txt")));
  for (const privatePath of ["config", "build", "tests", "node_modules", ".env"]) {
    assert.ok(!fs.existsSync(path.join(dist, privatePath)), `Do not publish ${privatePath}`);
  }
});
